name: Metrics

on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 * * * *"}]
  # Lines below let you run workflow manually and on each commit (optional)
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      # See action.yml for all options
      - uses: lowlighter/metrics@master
        with:
          # ... other options
          
          template: repository
          user: sharpview-io # Optional if you're the owner of target repository and you're using your own personal token
          repo: sharpview-io.github.io  # Repository name
    
          plugin_languages: yes
          plugin_languages_ignored: css                                 # List of languages to ignore
          plugin_languages_colors: "0:orange, javascript:#ff0000, ..."  # Make most used languages orange and JavaScript red
          plugin_languages_aliases: "JavaScript:JS, TypeScript:TS, ..." # Customize languages names with aliases
          plugin_languages_details: bytes-size, percentage              # Additionally display total bytes size and percentage
          plugin_languages_limit: 8                                     # Display up to 8 languages
          plugin_languages_sections: most-used, recently-used           # Display most used and recently used languages stats
          plugin_languages_indepth: no                                  # Get indepth stats (see documentation before enabling)
          plugin_languages_recent_load: 500                             # Load up to 500 events to compute recently used stats
          plugin_languages_recent_days: 7                               # Limit recently used stats to last week
          commits_authoring: lowlighter@users.noreply.github.com        # Surnames or email addresses used to identify your commits
          
          plugin_habits: yes
          plugin_habits_from: 200       # Use 200 events to compute habits
          plugin_habits_days: 14        # Keep only events from last 14 days
          plugin_habits_facts: yes      # Display facts section
          plugin_habits_charts: yes     # Display charts section
          plugin_habits_trim: yes       # Trim unused hours on daily chart
          config_timezone: Europe/Rome  # Set timezone
          
          plugin_licenses: yes
          plugin_licenses_setup: npm ci       # Command to setup target repository
          plugin_licenses_ratio: yes          # Display used licenses ratio
          plugin_licenses_legal: yes          # Display permissions, limitations and conditions
          
          plugin_followup: yes
          plugin_followup_sections: repositories #
          # Your GitHub token
          token: ${{ secrets.METRICS_TOKEN }}
